name: 'setup-fhem'
description: 'Install fhem, for further steps. Inspired by oher setup actions'
branding:
  icon: package
  color: green
inputs:
  mode:
    description: How to install the package?
    required: false
    default: debian
  runservice:    
    description: Let the default service run or stop it?
    required: false
    default: false
  
runs:
  using: "composite"
  steps:
    - name: Register debian.fhem repository
      if: inputs.mode == 'debian'
      run: |
        sudo wget -O /etc/apt/keyrings/deb.fhem.key https://debian.fhem.de/archive.key 
        sudo echo "deb [signed-by=/etc/apt/keyrings/deb.fhem.key] deb https://debian.fhem.de/nightly/ /" >>  /etc/apt/sources.list
      shell: bash

    - name: Install latest deb package
      if: inputs.mode == 'debian'
      run: |
        sudo apt-get update -qq
        sudo apt-get install fhem -y --no-install-recommends
      shell: bash
      
    - name: stop service fhem
      if: inputs.runservice == false
      run: |
        sudo systemctl stop fhem
      shell: bash
